# Exemple de service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mon-projet-service
spec:
  selector:
    app: mon-projet
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
